### PR TITLE
Fix #68 & remove underscore in publication.js

### LINKED ISSUE #68: wrong topLevelDocument in third Level find
My repo : https://github.com/darkship/test_publish_composite_update_array_bug

You will see that the number of items returned in <code>ItemsThroughSecondLevelPublish</code> is not the same as in <code>ItemsThroughThirdLevelPublish</code>

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Based on PR #85 to fix #68 & remove underscore in `publication.js`

### CODE REVIEW

File: lib/publication.js [hunk 1]
```diff
@@ -90,18 +89,38 @@ class Publication {
...
+        newArgs = parentArgs.slice(1)
+      } else {
+        newArgs = parentArgs
+      }
+
+      // Subsequent args are passed down from parent.
+      // These may have been updated by a grandparent publication.
+      newArgs.forEach(function (arg, i) {
+        publication.args[i + 1] = arg
+      })
```
Comment (reywood) [inline lib/publication.js:122]: could we get rid of line 106 and replace this forEach with:

```javascript
publication.args = [doc, ...newArgs];
```

Comment (StorytellerCZ) [reply lib/publication.js:122]: Yes!
